# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

dpr_sleep:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: "../../../../data/training/sleep-corpus.tsv"
  id_prefix: 'sleep:'
